### ISSUE TITLE
Read configuration file and generate routes

### ISSUE THREAD

**Issue by nikmel2803** [dh-center/deploy-server#3]
Пример конфигурационного файла (yaml):
```yaml
projects:
  - path: st-retrospect-api
    secret: super-secret-token
    deployScript: stRetrospectApiDeploy.sh
  - path: db-interface
    secret: super-secret-token1
    deployScript: dbInterfaceDeploy.sh
  - path: gulag
    secret: super-secret-token2
    deployScript: gulagDeploy.sh
```
Для каждого проекта должен генерироваться роут вида
`POST /:projectName/deploy`, принимающий параметр `secret`, содержащий секретную строку из конфига. В рамках этой задачи достаточно, чтобы роуты просто отвечали кодом 200.
Вот библиотека для парсинга `yaml` файла
https://www.npmjs.com/package/yaml
